all: server client
		
clean:
		rm -f client server

server: 
		g++ -o server server.cpp 

client: 
		g++ -o client client.cpp 

# debug:
# 	g++  -g3 ./*.cpp -o server
# fullDebug :
# 	g++  -Wall -g3 ./*.cpp -o server
# run:
# 	./server